// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/CXString.h:42
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXStringSet // 1
    {
        public IntPtr Strings;
        public uint Count;
    }
}
