// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXStringSet // 1
    {
        public IntPtr Strings;
        public uint Count;
    }
}
