// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/CXString.h:37
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXString // 1
    {
        public IntPtr data;
        public uint private_flags;
    }
}
