// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXString // 1
    {
        public IntPtr data;
        public uint private_flags;
    }
}
