// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CX_CXXAccessSpecifier // 1
    {
        _CXXInvalidAccessSpecifier = 0x0,
        _CXXPublic = 0x1,
        _CXXProtected = 0x2,
        _CXXPrivate = 0x3,
    }
}
