// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4032
    public enum CX_CXXAccessSpecifier // 1
    {
        _CXXInvalidAccessSpecifier = 0x0,
        _CXXPublic = 0x1,
        _CXXProtected = 0x2,
        _CXXPrivate = 0x3,
    }
}
