// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4052
    public enum CX_StorageClass // 1
    {
        _Invalid = 0x0,
        _None = 0x1,
        _Extern = 0x2,
        _Static = 0x3,
        _PrivateExtern = 0x4,
        _OpenCLWorkGroupLocal = 0x5,
        _Auto = 0x6,
        _Register = 0x7,
    }
}
