// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXAvailabilityKind // 2
    {
        _Available = 0x0,
        _Deprecated = 0x1,
        _NotAvailable = 0x2,
        _NotAccessible = 0x3,
    }
}
