// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4136
    public enum CXChildVisitResult // 1
    {
        _Break = 0x0,
        _Continue = 0x1,
        _Recurse = 0x2,
    }
}
