// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXCompletionChunkKind // 1
    {
        _Optional = 0x0,
        _TypedText = 0x1,
        _Text = 0x2,
        _Placeholder = 0x3,
        _Informative = 0x4,
        _CurrentParameter = 0x5,
        _LeftParen = 0x6,
        _RightParen = 0x7,
        _LeftBracket = 0x8,
        _RightBracket = 0x9,
        _LeftBrace = 0xa,
        _RightBrace = 0xb,
        _LeftAngle = 0xc,
        _RightAngle = 0xd,
        _Comma = 0xe,
        _ResultType = 0xf,
        _Colon = 0x10,
        _SemiColon = 0x11,
        _Equal = 0x12,
        _HorizontalSpace = 0x13,
        _VerticalSpace = 0x14,
    }
}
