// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:5530
    public enum CXCodeComplete_Flags // 0
    {
        _IncludeMacros = 0x1,
        _IncludeCodePatterns = 0x2,
        _IncludeBriefComments = 0x4,
        _SkipPreamble = 0x8,
        _IncludeCompletionsWithFixIts = 0x10,
    }
}
