// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXCompletionContext // 0
    {
        _Unexposed = 0x0,
        _AnyType = 0x1,
        _AnyValue = 0x2,
        _ObjCObjectValue = 0x4,
        _ObjCSelectorValue = 0x8,
        _CXXClassTypeValue = 0x10,
        _DotMemberAccess = 0x20,
        _ArrowMemberAccess = 0x40,
        _ObjCPropertyAccess = 0x80,
        _EnumTag = 0x100,
        _UnionTag = 0x200,
        _StructTag = 0x400,
        _ClassTag = 0x800,
        _Namespace = 0x1000,
        _NestedNameSpecifier = 0x2000,
        _ObjCInterface = 0x4000,
        _ObjCProtocol = 0x8000,
        _ObjCCategory = 0x10000,
        _ObjCInstanceMessage = 0x20000,
        _ObjCClassMessage = 0x40000,
        _ObjCSelectorName = 0x80000,
        _MacroName = 0x100000,
        _NaturalLanguage = 0x200000,
        _IncludedFile = 0x400000,
        _Unknown = 0x7fffff,
    }
}
