// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:179
    public enum CXCursor_ExceptionSpecificationKind // 0
    {
        _None = 0x0,
        _DynamicNone = 0x1,
        _Dynamic = 0x2,
        _MSAny = 0x3,
        _BasicNoexcept = 0x4,
        _ComputedNoexcept = 0x5,
        _Unevaluated = 0x6,
        _Uninstantiated = 0x7,
        _Unparsed = 0x8,
        _NoThrow = 0x9,
    }
}
