// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:750
    public enum CXDiagnosticSeverity // 1
    {
        _Ignored = 0x0,
        _Note = 0x1,
        _Warning = 0x2,
        _Error = 0x3,
        _Fatal = 0x4,
    }
}
