// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXDiagnosticDisplayOptions // 0
    {
        _DisplaySourceLocation = 0x1,
        _DisplayColumn = 0x2,
        _DisplaySourceRanges = 0x4,
        _DisplayOption = 0x8,
        _DisplayCategoryId = 0x10,
        _DisplayCategoryName = 0x20,
    }
}
