// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:907
    public enum CXDiagnosticDisplayOptions // 0
    {
        _DisplaySourceLocation = 0x1,
        _DisplayColumn = 0x2,
        _DisplaySourceRanges = 0x4,
        _DisplayOption = 0x8,
        _DisplayCategoryId = 0x10,
        _DisplayCategoryName = 0x20,
    }
}
