// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:5929
    public enum CXEvalResultKind // 1
    {
        _Int = 0x1,
        _Float = 0x2,
        _ObjCStrLiteral = 0x3,
        _StrLiteral = 0x4,
        _CFStr = 0x5,
        _Other = 0x6,
        _UnExposed = 0x0,
    }
}
