// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:282
    public enum CXGlobalOptFlags // 1
    {
        _None = 0x0,
        _ThreadBackgroundPriorityForIndexing = 0x1,
        _ThreadBackgroundPriorityForEditing = 0x2,
        _ThreadBackgroundPriorityForAll = 0x3,
    }
}
