// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6410
    public enum CXIdxEntityRefKind // 1
    {
        _Direct = 0x1,
        _Implicit = 0x2,
    }
}
