// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxDeclInfoFlags // 1
    {
        _Skipped = 0x1,
    }
}
