// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6260
    public enum CXIdxEntityLanguage // 1
    {
        _None = 0x0,
        _C = 0x1,
        _ObjC = 0x2,
        _CXX = 0x3,
        _Swift = 0x4,
    }
}
