// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6320
    public enum CXIdxDeclInfoFlags // 1
    {
        _Skipped = 0x1,
    }
}
