// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxEntityKind // 1
    {
        _Unexposed = 0x0,
        _Typedef = 0x1,
        _Function = 0x2,
        _Variable = 0x3,
        _Field = 0x4,
        _EnumConstant = 0x5,
        _ObjCClass = 0x6,
        _ObjCProtocol = 0x7,
        _ObjCCategory = 0x8,
        _ObjCInstanceMethod = 0x9,
        _ObjCClassMethod = 0xa,
        _ObjCProperty = 0xb,
        _ObjCIvar = 0xc,
        _Enum = 0xd,
        _Struct = 0xe,
        _Union = 0xf,
        _CXXClass = 0x10,
        _CXXNamespace = 0x11,
        _CXXNamespaceAlias = 0x12,
        _CXXStaticVariable = 0x13,
        _CXXStaticMethod = 0x14,
        _CXXInstanceMethod = 0x15,
        _CXXConstructor = 0x16,
        _CXXDestructor = 0x17,
        _CXXConversionFunction = 0x18,
        _CXXTypeAlias = 0x19,
        _CXXInterface = 0x1a,
    }
}
