// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxObjCContainerKind // 1
    {
        _ForwardRef = 0x0,
        _Interface = 0x1,
        _Implementation = 0x2,
    }
}
