// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxEntityLanguage // 1
    {
        _None = 0x0,
        _C = 0x1,
        _ObjC = 0x2,
        _CXX = 0x3,
        _Swift = 0x4,
    }
}
