// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6278
    public enum CXIdxEntityCXXTemplateKind // 1
    {
        _NonTemplate = 0x0,
        _Template = 0x1,
        _TemplatePartialSpecialization = 0x2,
        _TemplateSpecialization = 0x3,
    }
}
