// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxEntityCXXTemplateKind // 1
    {
        _NonTemplate = 0x0,
        _Template = 0x1,
        _TemplatePartialSpecialization = 0x2,
        _TemplateSpecialization = 0x3,
    }
}
