// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6350
    public enum CXIdxObjCContainerKind // 1
    {
        _ForwardRef = 0x0,
        _Interface = 0x1,
        _Implementation = 0x2,
    }
}
