// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxEntityRefKind // 1
    {
        _Direct = 0x1,
        _Implicit = 0x2,
    }
}
