// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6285
    public enum CXIdxAttrKind // 1
    {
        _Unexposed = 0x0,
        _IBAction = 0x1,
        _IBOutlet = 0x2,
        _IBOutletCollection = 0x3,
    }
}
