// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIdxAttrKind // 1
    {
        _Unexposed = 0x0,
        _IBAction = 0x1,
        _IBOutlet = 0x2,
        _IBOutletCollection = 0x3,
    }
}
