// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXIndexOptFlags // 1
    {
        _None = 0x0,
        _SuppressRedundantRefs = 0x1,
        _IndexFunctionLocalSymbols = 0x2,
        _IndexImplicitTemplateInstantiations = 0x4,
        _SuppressWarnings = 0x8,
        _SkipParsedBodiesInSession = 0x10,
    }
}
