// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6602
    public enum CXIndexOptFlags // 1
    {
        _None = 0x0,
        _SuppressRedundantRefs = 0x1,
        _IndexFunctionLocalSymbols = 0x2,
        _IndexImplicitTemplateInstantiations = 0x4,
        _SuppressWarnings = 0x8,
        _SkipParsedBodiesInSession = 0x10,
    }
}
