// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:2956
    public enum CXLanguageKind // 1
    {
        _Invalid = 0x0,
        _C = 0x1,
        _ObjC = 0x2,
        _CPlusPlus = 0x3,
    }
}
