// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:2805
    public enum CXLinkageKind // 1
    {
        _Invalid = 0x0,
        _NoLinkage = 0x1,
        _Internal = 0x2,
        _UniqueExternal = 0x3,
        _External = 0x4,
    }
}
