// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXLinkageKind // 1
    {
        _Invalid = 0x0,
        _NoLinkage = 0x1,
        _Internal = 0x2,
        _UniqueExternal = 0x3,
        _External = 0x4,
    }
}
