// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:814
    public enum CXLoadDiag_Error // 1
    {
        _None = 0x0,
        _Unknown = 0x1,
        _CannotLoad = 0x2,
        _InvalidFile = 0x3,
    }
}
