// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4872
    public enum CXNameRefFlags // 0
    {
        _WantQualifier = 0x1,
        _WantTemplateArgs = 0x2,
        _WantSinglePiece = 0x4,
    }
}
