// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXNameRefFlags // 0
    {
        _WantQualifier = 0x1,
        _WantTemplateArgs = 0x2,
        _WantSinglePiece = 0x4,
    }
}
