// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXObjCDeclQualifierKind // 1
    {
        _None = 0x0,
        _In = 0x1,
        _Inout = 0x2,
        _Out = 0x4,
        _Bycopy = 0x8,
        _Byref = 0x10,
        _Oneway = 0x20,
    }
}
