// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4548
    public enum CXObjCDeclQualifierKind // 1
    {
        _None = 0x0,
        _In = 0x1,
        _Inout = 0x2,
        _Out = 0x4,
        _Bycopy = 0x8,
        _Byref = 0x10,
        _Oneway = 0x20,
    }
}
