// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4505
    public enum CXObjCPropertyAttrKind // 1
    {
        _noattr = 0x0,
        _readonly = 0x1,
        _getter = 0x2,
        _assign = 0x4,
        _readwrite = 0x8,
        _retain = 0x10,
        _copy = 0x20,
        _nonatomic = 0x40,
        _setter = 0x80,
        _atomic = 0x100,
        _weak = 0x200,
        _strong = 0x400,
        _unsafe_unretained = 0x800,
        _class = 0x1000,
    }
}
