// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4315
    public enum CXPrintingPolicyProperty // 2
    {
        _Indentation = 0x0,
        _SuppressSpecifiers = 0x1,
        _SuppressTagKeyword = 0x2,
        _IncludeTagDefinition = 0x3,
        _SuppressScope = 0x4,
        _SuppressUnwrittenScope = 0x5,
        _SuppressInitializers = 0x6,
        _ConstantArraySizeAsWritten = 0x7,
        _AnonymousTagLocations = 0x8,
        _SuppressStrongLifetime = 0x9,
        _SuppressLifetimeQualifiers = 0xa,
        _SuppressTemplateArgsInCXXConstructors = 0xb,
        _Bool = 0xc,
        _Restrict = 0xd,
        _Alignof = 0xe,
        _UnderscoreAlignof = 0xf,
        _UseVoidForZeroParams = 0x10,
        _TerseOutput = 0x11,
        _PolishForDeclaration = 0x12,
        _Half = 0x13,
        _MSWChar = 0x14,
        _IncludeNewlines = 0x15,
        _MSVCFormatting = 0x16,
        _ConstantsAsWritten = 0x17,
        _SuppressImplicitBase = 0x18,
        _FullyQualifiedName = 0x19,
        _LastProperty = 0x19,
    }
}
