// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:1568
    public enum CXReparse_Flags // 0
    {
        _None = 0x0,
    }
}
