// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:3984
    public enum CXRefQualifierKind // 1
    {
        _None = 0x0,
        _LValue = 0x1,
        _RValue = 0x2,
    }
}
