// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6079
    public enum CXResult // 1
    {
        _Success = 0x0,
        _Invalid = 0x1,
        _VisitBreak = 0x2,
    }
}
