// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXReparse_Flags // 0
    {
        _None = 0x0,
    }
}
