// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:1489
    public enum CXSaveError // 0
    {
        _None = 0x0,
        _Unknown = 0x1,
        _TranslationErrors = 0x2,
        _InvalidTU = 0x3,
    }
}
