// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXSaveTranslationUnit_Flags // 0
    {
        _None = 0x0,
    }
}
