// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXTemplateArgumentKind // 1
    {
        _Null = 0x0,
        _Type = 0x1,
        _Declaration = 0x2,
        _NullPtr = 0x3,
        _Integral = 0x4,
        _Template = 0x5,
        _TemplateExpansion = 0x6,
        _Expression = 0x7,
        _Pack = 0x8,
        _Invalid = 0x9,
    }
}
