// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:2972
    public enum CXTLSKind // 1
    {
        _None = 0x0,
        _Dynamic = 0x1,
        _Static = 0x2,
    }
}
