// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:4915
    public enum CXTokenKind // 1
    {
        _Punctuation = 0x0,
        _Keyword = 0x1,
        _Identifier = 0x2,
        _Literal = 0x3,
        _Comment = 0x4,
    }
}
