// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXTokenKind // 1
    {
        _Punctuation = 0x0,
        _Keyword = 0x1,
        _Identifier = 0x2,
        _Literal = 0x3,
        _Comment = 0x4,
    }
}
