// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:3870
    public enum CXTypeLayoutError // 0
    {
        _Invalid = unchecked((int)0xffffffff),
        _Incomplete = unchecked((int)0xfffffffe),
        _Dependent = unchecked((int)0xfffffffd),
        _NotConstantSize = unchecked((int)0xfffffffc),
        _InvalidFieldName = unchecked((int)0xfffffffb),
        _Undeduced = unchecked((int)0xfffffffa),
    }
}
