// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXTypeLayoutError // 0
    {
        _Invalid = unchecked((int)0xffffffff),
        _Incomplete = unchecked((int)0xfffffffe),
        _Dependent = unchecked((int)0xfffffffd),
        _NotConstantSize = unchecked((int)0xfffffffc),
        _InvalidFieldName = unchecked((int)0xfffffffb),
        _Undeduced = unchecked((int)0xfffffffa),
    }
}
