// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:3835
    public enum CXTypeNullabilityKind // 1
    {
        _NonNull = 0x0,
        _Nullable = 0x1,
        _Unspecified = 0x2,
        _Invalid = 0x3,
    }
}
