// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXTypeNullabilityKind // 1
    {
        _NonNull = 0x0,
        _Nullable = 0x1,
        _Unspecified = 0x2,
        _Invalid = 0x3,
    }
}
