// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6069
    public enum CXVisitorResult // 2
    {
        _Break = 0x0,
        _Continue = 0x1,
    }
}
