// This source code was generated by ClangCaster

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:2828
    public enum CXVisibilityKind // 1
    {
        _Invalid = 0x0,
        _Hidden = 0x1,
        _Protected = 0x2,
        _Default = 0x3,
    }
}
