// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXErrorCode // 9
    {
        _Success = 0x0,
        _Failure = 0x1,
        _Crashed = 0x2,
        _InvalidArguments = 0x3,
        _ASTReadError = 0x4,
    }
}
