// This source code was generated by ClangCaster

namespace CIndex
{
    public static partial class C
    {
        // C:/Program Files/LLVM/include/clang-c/Index.h:35
        public const int CINDEX_VERSION_MAJOR = unchecked((int)0);

        // C:/Program Files/LLVM/include/clang-c/Index.h:36
        public const int CINDEX_VERSION_MINOR = unchecked((int)59);

        // C:/Program Files/LLVM/include/clang-c/Index.h:42
        public const int CINDEX_VERSION = unchecked((int)CINDEX_VERSION_MAJOR * 10000 + CINDEX_VERSION_MINOR);

    }
}
