// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXCallingConv // 1
    {
        _Default = 0x0,
        _C = 0x1,
        _X86StdCall = 0x2,
        _X86FastCall = 0x3,
        _X86ThisCall = 0x4,
        _X86Pascal = 0x5,
        _AAPCS = 0x6,
        _AAPCS_VFP = 0x7,
        _X86RegCall = 0x8,
        _IntelOclBicc = 0x9,
        _Win64 = 0xa,
        _X86_64Win64 = 0xa,
        _X86_64SysV = 0xb,
        _X86VectorCall = 0xc,
        _Swift = 0xd,
        _PreserveMost = 0xe,
        _PreserveAll = 0xf,
        _AArch64VectorCall = 0x10,
        _Invalid = 0x64,
        _Unexposed = 0xc8,
    }
}
