// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXDiagnosticSeverity // 1
    {
        _Ignored = 0x0,
        _Note = 0x1,
        _Warning = 0x2,
        _Error = 0x3,
        _Fatal = 0x4,
    }
}
