// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXLanguageKind // 1
    {
        _Invalid = 0x0,
        _C = 0x1,
        _ObjC = 0x2,
        _CPlusPlus = 0x3,
    }
}
