// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXResult // 1
    {
        _Success = 0x0,
        _Invalid = 0x1,
        _VisitBreak = 0x2,
    }
}
