// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXSaveError // 0
    {
        _None = 0x0,
        _Unknown = 0x1,
        _TranslationErrors = 0x2,
        _InvalidTU = 0x3,
    }
}
