// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXSymbolRole // 1
    {
        _None = 0x0,
        _Declaration = 0x1,
        _Definition = 0x2,
        _Reference = 0x4,
        _Read = 0x8,
        _Write = 0x10,
        _Call = 0x20,
        _Dynamic = 0x40,
        _AddressOf = 0x80,
        _Implicit = 0x100,
    }
}
