// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    public enum CXTLSKind // 1
    {
        _None = 0x0,
        _Dynamic = 0x1,
        _Static = 0x2,
    }
}
