// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXChildVisitResult // 1
    {
        _Break = 0x0,
        _Continue = 0x1,
        _Recurse = 0x2,
    }
}
