// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXGlobalOptFlags // 1
    {
        _None = 0x0,
        _ThreadBackgroundPriorityForIndexing = 0x1,
        _ThreadBackgroundPriorityForEditing = 0x2,
        _ThreadBackgroundPriorityForAll = 0x3,
    }
}
