// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXIdxEntityRefKind // 1
    {
        _Direct = 0x1,
        _Implicit = 0x2,
    }
}
