// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXIdxAttrKind // 1
    {
        _Unexposed = 0x0,
        _IBAction = 0x1,
        _IBOutlet = 0x2,
        _IBOutletCollection = 0x3,
    }
}
