// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXIdxDeclInfoFlags // 1
    {
        _Skipped = 0x1,
    }
}
