// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXRefQualifierKind // 1
    {
        _None = 0x0,
        _LValue = 0x1,
        _RValue = 0x2,
    }
}
