// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXReparse_Flags // 0
    {
        CXReparse_None = 0x0,
    }
}
