// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXSaveTranslationUnit_Flags // 0
    {
        CXSaveTranslationUnit_None = 0x0,
    }
}
