// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXTranslationUnit_Flags // 0
    {
        _None = 0x0,
        _DetailedPreprocessingRecord = 0x1,
        _Incomplete = 0x2,
        _PrecompiledPreamble = 0x4,
        _CacheCompletionResults = 0x8,
        _ForSerialization = 0x10,
        _CXXChainedPCH = 0x20,
        _SkipFunctionBodies = 0x40,
        _IncludeBriefCommentsInCodeCompletion = 0x80,
        _CreatePreambleOnFirstParse = 0x100,
        _KeepGoing = 0x200,
        _SingleFileParse = 0x400,
        _LimitSkipFunctionBodiesToPreamble = 0x800,
        _IncludeAttributedTypes = 0x1000,
        _VisitImplicitAttributes = 0x2000,
        _IgnoreNonErrorsFromIncludedFiles = 0x4000,
        _RetainExcludedConditionalBlocks = 0x8000,
    }
}
