// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXTUResourceUsageKind // 2
    {
        _AST = 0x1,
        _Identifiers = 0x2,
        _Selectors = 0x3,
        _GlobalCompletionResults = 0x4,
        _SourceManagerContentCache = 0x5,
        _AST_SideTables = 0x6,
        _SourceManager_Membuffer_Malloc = 0x7,
        _SourceManager_Membuffer_MMap = 0x8,
        _ExternalASTSource_Membuffer_Malloc = 0x9,
        _ExternalASTSource_Membuffer_MMap = 0xa,
        _Preprocessor = 0xb,
        _PreprocessingRecord = 0xc,
        _SourceManager_DataStructures = 0xd,
        _Preprocessor_HeaderSearch = 0xe,
        _MEMORY_IN_BYTES_BEGIN = 0x1,
        _MEMORY_IN_BYTES_END = 0xe,
        _First = 0x1,
        _Last = 0xe,
    }
}
