// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace libclang {
    public enum CXVisibilityKind // 1
    {
        _Invalid = 0x0,
        _Hidden = 0x1,
        _Protected = 0x2,
        _Default = 0x3,
    }
}
