// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXCompletionResult // 1
    {
        public CXCursorKind CursorKind;
        public IntPtr CompletionString;
    }
}
