// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXCodeCompleteResults // 1
    {
        public IntPtr Results;
        public uint NumResults;
    }
}
