// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:5446
    [StructLayout(LayoutKind.Sequential)]
    public struct CXCodeCompleteResults // 1
    {
        public IntPtr Results;
        public uint NumResults;
    }
}
