// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:5108
    [StructLayout(LayoutKind.Sequential)]
    public struct CXCompletionResult // 1
    {
        public CXCursorKind CursorKind;
        public IntPtr CompletionString;
    }
}
