// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXCursor // 1
    {
        public CXCursorKind kind;
        public int xdata;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)] public IntPtr[] data;
    }
}
