// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:2992
    [StructLayout(LayoutKind.Sequential)]
    public struct CXCursorSetImpl // 1
    {
    }
}
