// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6074
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXCursorAndRangeVisitor // 1
    {
        public IntPtr context;
        public IntPtr visit;
    }
}
