// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:2688
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXCursor // 1
    {
        public CXCursorKind kind;
        public int xdata;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)] public IntPtr[] data;
    }
}
