// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:374
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXFileUniqueID // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)] public ulong[] data;
    }
}
