// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxCXXClassDeclInfo // 1
    {
        public IntPtr declInfo;
        public IntPtr bases;
        public uint numBases;
    }
}
