// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxEntityInfo // 1
    {
        public CXIdxEntityKind kind;
        public CXIdxEntityCXXTemplateKind templateKind;
        public CXIdxEntityLanguage lang;
        public IntPtr name;
        public IntPtr USR;
        public CXCursor cursor;
        public IntPtr attributes;
        public uint numAttributes;
    }
}
