// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:6373
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxObjCProtocolRefListInfo // 1
    {
        public IntPtr protocols;
        public uint numProtocols;
    }
}
