// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxImportedASTFileInfo // 1
    {
        public IntPtr file;
        public IntPtr module;
        public CXIdxLoc loc;
        public int isImplicit;
    }
}
