// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6204
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxImportedASTFileInfo // 1
    {
        public IntPtr file;
        public IntPtr module;
        public CXIdxLoc loc;
        public int isImplicit;
    }
}
