// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxObjCContainerDeclInfo // 1
    {
        public IntPtr declInfo;
        public CXIdxObjCContainerKind kind;
    }
}
