// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6367
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxObjCProtocolRefInfo // 1
    {
        public IntPtr protocol;
        public CXCursor cursor;
        public CXIdxLoc loc;
    }
}
