// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxIncludedFileInfo // 1
    {
        public CXIdxLoc hashLoc;
        public IntPtr filename;
        public IntPtr file;
        public int isImport;
        public int isAngled;
        public int isModuleImport;
    }
}
