// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxEntityRefInfo // 1
    {
        public CXIdxEntityRefKind kind;
        public CXCursor cursor;
        public CXIdxLoc loc;
        public IntPtr referencedEntity;
        public IntPtr parentEntity;
        public IntPtr container;
        public CXSymbolRole role;
    }
}
