// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6356
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxObjCContainerDeclInfo // 1
    {
        public IntPtr declInfo;
        public CXIdxObjCContainerKind kind;
    }
}
