// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6313
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxIBOutletCollectionAttrInfo // 1
    {
        public IntPtr attrInfo;
        public IntPtr objcClass;
        public CXCursor classCursor;
        public CXIdxLoc classLoc;
    }
}
