// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxBaseClassInfo // 1
    {
        public IntPtr _base;
        public CXCursor cursor;
        public CXIdxLoc loc;
    }
}
