// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:6171
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxLoc // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)] public IntPtr[] ptr_data;
        public uint int_data;
    }
}
