// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6378
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxObjCInterfaceDeclInfo // 1
    {
        public IntPtr containerInfo;
        public IntPtr superInfo;
        public IntPtr protocols;
    }
}
