// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6392
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxObjCPropertyDeclInfo // 1
    {
        public IntPtr declInfo;
        public IntPtr getter;
        public IntPtr setter;
    }
}
