// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxObjCInterfaceDeclInfo // 1
    {
        public IntPtr containerInfo;
        public IntPtr superInfo;
        public IntPtr protocols;
    }
}
