// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxObjCProtocolRefListInfo // 1
    {
        public IntPtr protocols;
        public uint numProtocols;
    }
}
