// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:6398
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxCXXClassDeclInfo // 1
    {
        public IntPtr declInfo;
        public IntPtr bases;
        public uint numBases;
    }
}
