// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:6292
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXIdxAttrInfo // 1
    {
        public CXIdxAttrKind kind;
        public CXCursor cursor;
        public CXIdxLoc loc;
    }
}
