// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXIdxObjCPropertyDeclInfo // 1
    {
        public IntPtr declInfo;
        public IntPtr getter;
        public IntPtr setter;
    }
}
