// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:461
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXSourceLocation // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)] public IntPtr[] ptr_data;
        public uint int_data;
    }
}
