// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex
{
    // C:/Program Files/LLVM/include/clang-c/Index.h:705
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CXSourceRangeList // 1
    {
        public uint count;
        public IntPtr ranges;
    }
}
