// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXSourceRangeList // 1
    {
        public uint count;
        public IntPtr ranges;
    }
}
