// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXSourceLocation // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)] public IntPtr[] ptr_data;
        public uint int_data;
    }
}
