// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:472
    [StructLayout(LayoutKind.Sequential)]
    public struct CXSourceRange // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)] public IntPtr[] ptr_data;
        public uint begin_int_data;
        public uint end_int_data;
    }
}
