// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:4945
    [StructLayout(LayoutKind.Sequential)]
    public struct CXToken // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)] public uint[] int_data;
        public IntPtr ptr_data;
    }
}
