// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXToken // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)] public uint[] int_data;
        public IntPtr ptr_data;
    }
}
