// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:1664
    [StructLayout(LayoutKind.Sequential)]
    public struct CXTUResourceUsageEntry // 1
    {
        public CXTUResourceUsageKind kind;
        public uint amount;
    }
}
