// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:1675
    [StructLayout(LayoutKind.Sequential)]
    public struct CXTUResourceUsage // 1
    {
        public IntPtr data;
        public uint numEntries;
        public IntPtr entries;
    }
}
