// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXTUResourceUsageEntry // 1
    {
        public CXTUResourceUsageKind kind;
        public uint amount;
    }
}
