// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXTUResourceUsage // 1
    {
        public IntPtr data;
        public uint numEntries;
        public IntPtr entries;
    }
}
