// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXType // 1
    {
        public CXTypeKind kind;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)] public IntPtr[] data;
    }
}
