// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:106
    [StructLayout(LayoutKind.Sequential)]
    public struct CXUnsavedFile // 8
    {
        public IntPtr Filename;
        public IntPtr Contents;
        public uint Length;
    }
}
