// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    [StructLayout(LayoutKind.Sequential)]
    public struct CXVersion // 1
    {
        public int Major;
        public int Minor;
        public int Subminor;
    }
}
