// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace CIndex {
    // C:/Program Files/LLVM/include/clang-c/Index.h:154
    [StructLayout(LayoutKind.Sequential)]
    public struct CXVersion // 1
    {
        public int Major;
        public int Minor;
        public int Subminor;
    }
}
